### ISSUE TITLE
Requesting for Android Pentesting tools in Nightingale

### ISSUE THREAD

**Issue by sindhuhack** [RAJANAGORI/Nightingale#5]
Hi Raja,

You have done a great job by creating Nightingale docker images with all web penetration based tools under one roof. This makes our tasks so simple without installing any dependencies. similar to that can you please add Android penetration tools in Nightingale.

Tools:
MOBSF, Apktool, JD-GUI, Dex2jar, objection, Frida, ADB platform tools, Drozer, d2j-dex2jar

Thanks,
Yogi

**Comment by RAJANAGORI** [comment]
Hey,
Thanks for raising the issues,
Changes are done now, have fun with this tool. 💥
