### ISSUE TITLE
[TOOL REQUEST]: interactsh

### ISSUE THREAD

**Issue by Dr-Savage** [RAJANAGORI/Nightingale#63]
### Tool Name

interactsh

### GitHub Repository

https://github.com/projectdiscovery/interactsh

### Type

Web VAPT

### Purpose of the Tool

for use of Out of band connections.

**Comment by RAJANAGORI** [comment]
Hi @Dr-Savage (Shlok), your request tool has been added. You can use the below image
docker pull ghcr.io/rajanagori/nightingle:stable

Thank you for using this tool 😄
<img width="465" alt="Screenshot 2024-11-07 at 11 58 40 PM" src="https://github.com/user-attachments/assets/da21631b-57d3-4dd7-83f4-83217a555a8e">
