### ISSUE TITLE
[TOOL REQUEST]: hashcat for cracking the passwords

### ISSUE THREAD

**Issue by Dr-Savage** [RAJANAGORI/Nightingale#77]
### Tool Name

hashcat

### GitHub Repository

https://github.com/hashcat/hashcat

### Type

Web VAPT

### Purpose of the Tool

crack the hashes, decrypt the tokens

**Comment by RAJANAGORI** [comment]
Hi @Dr-Savage (Shlok),

The tool you requested has been successfully added! You can now pull the image using the following
`docker pull ghcr.io/rajanagori/nightingle:stable`

Thank you for using this tool! 😄 If you have any other questions or issues, feel free to reach out.

Best regards,
Raja Nagori
![image](https://github.com/user-attachments/assets/4eaf9b6c-38ca-4b9d-80be-0477924b8376)
